### ISSUE TITLE
Value shape mismatch in LinearMatrix function

### ISSUE THREAD

**Issue by jvesely** [PrincetonUniversity/PsyNeuLink#1247]
adding:
```
        print("OWNER: ", self.owner)
        print("DEFAULT: ", self.defaults.value)
        print("VALUE: ", self.value)
```
prints:
```
OWNER:  (MappingProjection MappingProjection from a-1[RESULTS] to b-1[InputState-0])
DEFAULT:  0.0
VALUE:  [0.]
OWNER:  (MappingProjection MappingProjection from a-2[RESULTS] to b-2[InputState-0])
DEFAULT:  0.0
VALUE:  [0.]
OWNER:  (MappingProjection MappingProjection from a-2[RESULTS] to b-2[InputState-0])
DEFAULT:  0.0
VALUE:  [0.]
```
in bi_stable_percept tests.

**Comment by jvesely** [comment]
somehow these only pop up in bi_stable_percpet tests, although other tests use mapping projections

**Comment by kmantel** [comment]
I'm still looking into this, but it may have something to do with the Identity function swapping. If you check the values again after this line `res = bp_comp.run(input_dict, num_trials=10, bin_execute=mode)`, you'll see that the function for that mapping projection is an Identity function. So something is happening during run causing the reassignment. It doesn't explain the mismatch before the .run call, though. Not sure about that one yet because on the first instantiation, it looks like the LinearMatrix function has the correct/matching default and value

**Comment by kmantel** [comment]
Ok, this in particular wasn't related to that, although I think a similar issue is possible with the Identity switching. The mapping projection's matrix parameter state has its function reassigned during _instantiate_parameter_states, and in many cases the shape is changed, but the default value/value for the parameter state wasn't updated. This ends up being used in linearmatrix.py:3018, affecting the shape of its return value. I pushed a commit to fix this

**Comment by jvesely** [comment]
Thanks, I confirmed that 9ffbc322f5e1dcf111ecd242017cdcf59d9ee4fa fixes the issue and was able to remove the workaround.
