### ISSUE TITLE
Docs building runs on selfhosted runners

### ISSUE THREAD

**Issue by davidt0x** [PrincetonUniversity/PsyNeuLink#2526]
I just noticed that building of docs runs on the self hosted runners for macos. Am I wrong to think we should probably not do this because it seems like it can inadvertently lead to the tests (for macos) being run on cloud instances as a fallback? If we want to avoid this, we could set a special label like macos-self-hosted (instead of macos-latest) for these CI workflow and get rid of macos-latest. Or maybe there is a better way? 

Also, why do we build docs on all platforms and so many versions of Python? Shouldn't the runs on just be set to one python version and one OS?

**Comment by jvesely** [comment]
This is a side effect of a bigger issue of implementing exclusive use of self-hosted runners if available (i.e. wait for self-hosted runners before falling back to cloud). waiting 10more mins for a documentation job is just a minor part of that.

Unconditional use of custom labels is a no-go because it breaks CI for forks.

A related issue: a more controlled handling of OS image version. We currently use `-latest` and are at the merci of github wrt to changing OS version. This caused problems before [0]. self-hosted runners should ideally report the OS version that this running on them (unless the use VM/containers and can use custom OS image).
This would allow us to e.g. keep main CI jobs on macos-11 and bumpy the docs jobs to macos-12 (or the other way around) this would effectively remove doc jobs from the self-hosted runners as a workaround until a proper matrix manipulation based on the environment is implemented.

Documentation building is supported and expected to work on all platforms and the supported Python versions. This was broken before and will be broken again unless it's tested as part of CI. A single variant is used to update the webpage.

[0] https://github.com/actions/runner-images/issues/4230

**Comment by jvesely** [comment]
This has been running for some time. Closing
